# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Composer dependencies (PHP packages)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    reviewers:
      - "copilot"
    labels:
      - "dependencies"
      - "composer"
      - "automated"
      - "auto-release"
    commit-message:
      prefix: "🔧"
      prefix-development: "🔧"
      include: "scope"
    # Group minor and patch updates together
    groups:
      composer-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Critical packages - always create separate PRs
    ignore:
      - dependency-name: "silverassist/wp-settings-hub"
        update-types: ["version-update:semver-major"]
      - dependency-name: "silverassist/wp-github-updater"
        update-types: ["version-update:semver-major"]

  # npm dependencies (JavaScript packages)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    reviewers:
      - "copilot"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
      - "auto-release"
    commit-message:
      prefix: "🔧"
      prefix-development: "🔧"
      include: "scope"
    # Group minor and patch updates
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates that might break things
    ignore:
      - dependency-name: "grunt"
        update-types: ["version-update:semver-major"]
      - dependency-name: "postcss"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 3
    reviewers:
      - "copilot"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
      - "auto-release"
    commit-message:
      prefix: "🔧"
      include: "scope"
